version: "3.8"

services:
  constructor-service:
    build:
      context: ./constructor-service
      dockerfile: Dockerfile
    container_name: constructor-service
    # ports:
    #   - "${CONSTRUCTOR_SERVICE_PORT}:${CONSTRUCTOR_SERVICE_PORT}"
    volumes:
      - ./constructor-service/schemas:/app/schemas
    environment:
      SERVICE_PORT: ${CONSTRUCTOR_SERVICE_PORT}

  chat-postgres:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${CHAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHAT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CHAT_POSTGRES_DB} 
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CHAT_POSTGRES_USER} -d ${CHAT_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  chat-service:
    build: ./chat-service
    container_name: chat-service
    restart: always
    depends_on:
      chat-postgres:
        condition: service_healthy
      chat-redis:
        condition: service_started
      ai-agent:
        condition: service_started
    environment:
      POSTGRES_HOST: ${CHAT_POSTGRES_HOST}
      POSTGRES_PORT: ${CHAT_POSTGRES_PORT}
      POSTGRES_USER: ${CHAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHAT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CHAT_POSTGRES_DB}
      REDIS_HOST: chat-redis
      REDIS_PORT: ${CHAT_REDIS_PORT}
      SERVICE_PORT: ${CHAT_SERVICE_PORT}
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    volumes:
      - ./chat-service/alembic:/app/alembic

  chat-redis:
    image: redis:7-alpine
    container_name: chat-redis
    command: redis-server --port ${CHAT_REDIS_PORT} --appendonly yes --save 60 1 --protected-mode no
    # ports:
    #   - "${CHAT_REDIS_PORT}:${CHAT_REDIS_PORT}"
    volumes:
      - chat_redis_data:/data

  ai-agent:
    build: ./ai-agent
    container_name: ai-agent
    environment:
      REDIS_HOST: chat-redis
      REDIS_PORT: ${CHAT_REDIS_PORT}
      LLM_URL: ${LLM_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      MODEL_NAME: ${MODEL_NAME}
      MAIN_SYSTEM_PROMPT: ${MAIN_SYSTEM_PROMPT}
    depends_on:
      - chat-redis
    restart: unless-stopped

volumes:
  chat_postgres_data:
  chat_redis_data:
